### ISSUE TITLE
temp sensor of echo dot 4 dont showing

### ISSUE THREAD

**Issue by Maorbz** [alandtse/alexa_media_player#2351]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**cant see my echo dot 4 temperature sensor**

**show temp sensor of my echo dot 4 in my home assistant**

1. Go to 'settings'
2. Click on 'devices & services'
3. Click on 'Alexa media player'
4. Click on 'configure'
5. checked the box 'Include devices connected via Echo'
6. the temp sensor not added to my entities

**To add temp sensor of echo dot 4 **

![123](https://github.com/user-attachments/assets/64909b19-ecb2-4e92-8d99-3e2e6cfff62a)

**System details**

- Home-assistant (version): 2024.7.3
- alexa_media (version from `const.py` or HA startup): 4.11.4
- alexapy (version from `pip show alexapy` or HA startup): 3.12
- Amazon [2FA is enabled] : YES

**Logs**

![123](https://github.com/user-attachments/assets/7f125e7e-3a63-4afa-9a42-b26e1d296959)

**Comment by SConaway** [comment]
Looks like this is being tracked here: https://github.com/alandtse/alexa_media_player/issues/2344

**Comment by ViZeta76** [comment]
I have the same issue, the 4.11.5 release didn't fix the problem

**Comment by Maorbz** [comment]
thank you my friend...

Do you think that will be fixed?

‫בתאריך יום ג׳, 23 ביולי 2024 ב-10:46 מאת ‪Vz‬‏ ***@***.***
‬‏>:‬

**Comment by ViZeta76** [comment]
I hope so. I updated from 4.10.3 directly to the latest (4.11.5) and I have this issue. I don't know if it's present in all 4.11.*

**Comment by danielbrunt57** [comment]
Correct me if I'm wrong but as far as I know, the Echo **_Dot_** 4 does not have a temperature sensor, only it's bigger brother the Echo 4 (w/Zigbee hub).  I just enabled `Include devices connected via Echo` (Alexa Media Player v4.11.5), saved settings, an integration reload automatically occurred and I now have the Echo 4 temperature sensor...

![image](https://github.com/user-attachments/assets/bca45343-b846-4ed2-9329-a3e36eba2152)

But not in the Echo **_Dot_** 4...
![image](https://github.com/user-attachments/assets/94deba16-f464-4af0-b44c-13e36640ee6d)

![20240723_084857](https://github.com/user-attachments/assets/c307ab14-e4b2-45ec-91bf-e164155c929d)

**Comment by ViZeta76** [comment]
In my case I was referring to the echo device.,the big one.
Actually, i restored the old release, but thank you, i will follow your suggestion by ticking the item.

**Comment by danielbrunt57** [comment]
@Maorbz 
> alexa_media (version from const.py or HA startup): 4.11.4

Your issue should be solved by 4.11.5.  Please confirm.
Thanks.

**Comment by Jeppedy** [comment]
It looks like the update turned off that setting.  All was working fine with temp display before the update, then none of the Dots were reporting temp.  I turned on "include devices connected via Echo" and they are working again.
BTW, I have Echo Dot 5th gen.  They have a temperature sensor.

**Comment by vjbalex** [comment]
I have 1 Echo 4 and 3 Echo Dots (5th Gen) All have temprature sensors. Also an Echo Flex (I know it's old but serves a purpose) with a 3rd Reality USB night light AMP passes to HA as a light. All were working fine until v4.11.5
Previous suggestions did not work for me. Checking the "Include devices connected via Echo" creates an error wanting Included and Excluded Devices. (Previously "This Device" was excluded in configuration.yaml (where that came from I have no idea). If I delete that exclusion from configuration.yaml, reload Yaml and restart HA, I can use the "Include devices connected via Echo" , but the issue isn't always fixed at that point and if it is, only temporarily. A short time later,  they will become "Unavailable" again.
The only thing that brings them back to life is to Delete the "Integration entries" on the AMP Integration page (I only have 1) and go through the Configuration process again, redo any modifications I did i.e. icon selection. HOWEVER, it does not survive an HA reboot. I have to keep re-doing the process every time.
A previous poster suggested this is being tracked in issue #2344 which is similar/related. There is even a comment on the issue page that it is fixed.
I do very much appreciate the hard work and contributuions by HA developers and the community. It;s just that IMHO the temperature and light issue I and others are having is still a problem, not fixed and was broken by v4.11.5.

**Comment by danielbrunt57** [comment]
> BTW, I have Echo Dot 5th gen. They have a temperature sensor.

Thanks, that's good for me to know should I decide I want a temp sensor in a location with a Dot 4...

**Comment by woempiej** [comment]
> It looks like the update turned off that setting. All was working fine with temp display before the update, then none of the Dots were reporting temp. I turned on "include devices connected via Echo" and they are working again. BTW, I have Echo Dot 5th gen. They have a temperature sensor.

Reloading the integration manually let the temp sensors work again > No need to "!include".
I have to reload manually the past 4-5 updates to get temp sensors working again.

**Comment by Jeppedy** [comment]
Reload didn't solve it.  I had to re-enable that setting manually, then it
started working.

**Comment by Maorbz** [comment]
Dear daniel , i confirm that my issue has solved in version 4.11.5, can you
tell me what was the problem please?

בתאריך יום ד׳, 24 ביולי 2024, 06:39, מאת Daniel ***@***.***>:

**Comment by danielbrunt57** [comment]
> can you tell me what was the problem please?

Quite simply, I had moved the optional settings from the "options" key in `/config/.storage/core.config_entries` to the "data" key and had done most of the mods in config_flow.py.  I missed a piece of code in __init.py where it was still retrieving the settings from options: key which was now {} and was defaulting to the default settings.

![image](https://github.com/user-attachments/assets/812a2463-d006-4b6c-9f57-f5fe86044366)

This section was `config_entry.options.get` and the fix was to use `config_entry.data.get`:

![image](https://github.com/user-attachments/assets/bdd8aad2-3b40-4ec7-9be1-701fc83f9cac)

Since the options: key was now {}, it was populating the account values with the default settings ("", 1.5, 60, False and False) on a reload.

**Comment by danielbrunt57** [comment]
@alandtse Please close this as resolved.
