### ISSUE TITLE
No Alexa devices listed when installing the integration.

### ISSUE THREAD

**Issue by bkr1969** [alandtse/alexa_media_player#2430]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Alexa Media Player now finally installs, but there are no devices listed (I have 13 in my home). If I hit "RECONFIGURE" I get an error

**To Reproduce**

1. Install the Integration
2. See that no Alexa devices are listed
3. Hit "RECONFIGURE"

**Expected behavior**

I just want my devices to be listed and accessible as before the core update to 2024.8.0

**Screenshots**

**System details**

- Home-assistant (version): 12.4
- alexa_media (version from `const.py` or HA startup): 4.12.6
- alexapy (version from `pip show alexapy` or HA startup): WARNING: Package(s) not found: alexapy
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : N

**Logs**
```

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 07:14:25 (1 occurrences)
Last logged: 07:14:25

Error setting up entry brian@brianredmond.net - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 359, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 687, in login
    post_resp = await self._session.post(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 576, in _request
    raise err_exc_cls(url)
aiohttp.client_exceptions.InvalidUrlClientError: /errors/validateCaptcha

```

**Additional context**

**Comment by bevanting** [comment]
Did you install HA 2024.8.0 yesterday? I find that that was my problem. I rolled back to 2024.7.4 and it's working again.

**Comment by bkr1969** [comment]
I did.  I hate rolling back because I then have to jump through all the hoops of reconfiguring SmartThings.  I would rather the issue just be fixed.  Two of the related issues have already been closed as fixed with an integration update, but I am current on everything and it isn't working.

**Comment by Webguyatwork** [comment]
I have the same issue, same exact error logs. My integration broke prior to 2024.7.4, so I don't imagine rolling back will fix it. I've remove and successfully re-added the Alexa Media Player integration by validating the 2FA token, but it still won't load any devices.

**Comment by Webguyatwork** [comment]
And just as quickly as I stated my issue, I received the update to 4.12.6 of this integration and now it's back up and working again.

**Comment by bkr1969** [comment]
OK, so I'm not using 2FA.  Should that make a difference?  Because 4.12.6 did not fix my problem.

**Comment by sca075** [comment]
Guys there is a general problem with the dependencies see #2433 this should fix the boot of the integration and so far it worked by manually updating the manifest.json. Hope this helps.

**Comment by bkr1969** [comment]
![image](https://github.com/user-attachments/assets/6ba9161f-993d-4715-a19e-fecb80830921)

**Comment by bkr1969** [comment]
OK. The #2433 patch worked.  Thanks!
