### ISSUE TITLE
Alexa+ erratic with `alexa_media`

### ISSUE THREAD

**Issue by bturrie** [alandtse/alexa_media_player#3033]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

I'm using an early realease of  alexa+ as a longtime subscriber to amazon. After the "upgrade" at first i could not create an automation to send sounds to an Alexa device. Now previously working automations that used to send notifications to devices nlonger work

Previously working notifications to alexa devices no longer work. Theres no beep when I tru to change the volume and the notification does not happen

Create an automation that sends amzn-sfx  sounds or notifications to an Alexa device.

**Expected behavior**

I expected the echo to beep when I changed volume and then for it to speak my message. Neither happened.

**Screenshots**

There is noting at all in the logs

I'm running Ha 25.10.1
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2SV via Authenticator App](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (not 2SV OTP via SMS) enabled?  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by danielbrunt57** [comment]
I think your issue is much deeper than you think and it might be the general failure of AMP to reliably retrieve network details from Amazon as referenced in [issue #3032 ](https://github.com/alandtse/alexa_media_player/issues/3032).  Alexa Devices is also affected and it seems that Amazon may have once again changed their API.

**Comment by pbranly** [comment]
Hi Alexa devices integration is fixed with a beta  release
Ploease fix it with this Hacs integration

**Comment by bturrie** [comment]
> Hi Alexa devices integration is fixed with a beta release
> Please fix it with this Hacs integration
> 

I tried a workaround for my issue with Alexa+ using an Alexa routine. The routine appeared to fire without being triggered and sent it's response to an Echo different from the one specified in the routine. It seems perhaps that Alexa+ behavior is also erratic with Alexa routines.

**Comment by danielbrunt57** [comment]
Is this still an issue with AMP release v5.8.0?

**Comment by bturrie** [comment]
I tried alexa+ last week. I was still having significant issues with nearly all aspects of AMP (sounds, media TTS did not work. Neither did routines.  I guess that was before v5.8.0 came out though I'm not entirely certain of that.. Nevertheless,t I bailed back out of Alexa+ for the second time. That said, TTS still doesn't work after I swiatched back to Alexa on v5.8.0. Sounds and routines are back working at this point though.

**Comment by wiiNinja** [comment]
I was tempted to try Alexa+, but seeing this, I'm going to wait.

**Comment by danielbrunt57** [comment]
AMP with Alexa+ is currently unsupported at this time.
That said, I've signed up for the preview and will have a look at it when I can get it.

**Comment by danielbrunt57** [comment]
I now have Alexa+...

**Comment by danielbrunt57** [comment]
I've tested the following aspects of AMP with **_Alexa+_** and everything works exactly the same as it did with **_Alexa_**:

- TTS
- Alexa routines
- Play sounds
- Play Media
- Volume Up/Down/Set
- Next/Previous (Track)
- Play/Pause
- Play media
- Pause
- Stop
- Mute/Unmute
- Turn down/up volume
- Set volume
- Next/previous
- Set shuffle
