### ISSUE TITLE
The Integration Initialized but Failed to Fully Authenticate or Discover Devices

### ISSUE THREAD

**Issue by kiwibhoy** [alandtse/alexa_media_player#3132]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details** Home Assistant 2025.11.1 on Nobu Casa
Alexa - Integration version (5.7.13)
Alexa Echo Dot
I have been unsuccessful trying to use the integration and the log below is most common displayed after each time I to get the integration configured correctly:
This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/__init__.py:805
integration: Alexa Media Player (documentation, issues)
First occurred: 3:45:38 PM (2 occurrences)
Last logged: 3:45:38 PM

alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7f6aaba3c0>,), {'max_record_size': 10}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Cannot serialize non-str key None',)
alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f6aaba3c0>,), {}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Cannot serialize non-str key None',)

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2SV via Authenticator App](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (not 2SV OTP via SMS) enabled?  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

I've tried using AI but perhaps I'm not experienced enough to ask the right questions. Any help would be appreciated and hopefully I have followed Github protocols correctly its my first time

**Comment by jocamane** [comment]
### **Whenever I restart Home Assistant, these two errors appear:**

This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/__init__.py:805
integration: Alexa Media Player (documentation, issues)
First occurred: 08:59:40 (2 occurrences)
Last logged: 08:59:40

alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7f6dcbd6a0>,), {'max_record_size': 10}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Cannot serialize non-str key None',)

alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f6dcbd6a0>,), {}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Cannot serialize non-str key None',)



Installation method: Home Assistant OS
Core: 2025.10.4
Supervisor: 2025.11.1
Operating System: 16.2
AMP: 5.7.13

**Comment by steverumsby** [comment]
Same here. AMP has the list of echo devices, but not the zigbee devices connected to them. This is in the HA logs during startup:

Logger: alexapy.helpers
Source: runner.py:289
First occurred: 9:11:59 AM (2 occurrences)
Last logged: 9:11:59 AM

alexaapi.get_devices_gql((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",)
alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",)

This is with HA 2025.11.2 and AMP 5.7.13

**Comment by danielbrunt57** [comment]
> Same here. AMP has the list of echo devices, but not the zigbee devices connected to them. This is in the HA logs during startup:
> 
> Logger: alexapy.helpers Source: runner.py:289 First occurred: 9:11:59 AM (2 occurrences) Last logged: 9:11:59 AM
> 
> alexaapi.get_devices_gql((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",) alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",)
> 
> This is with HA 2025.11.2 and AMP 5.7.13

This is a completely different error that is the result of `get_network_devices` receiving error message "Too many requests" rather than a list of network endpoints that causes `get` to fail and is a known issue with a fix in progress and is not related to this issue.

**Comment by steverumsby** [comment]
> > Same here. AMP has the list of echo devices, but not the zigbee devices connected to them. This is in the HA logs during startup:
> > Logger: alexapy.helpers Source: runner.py:289 First occurred: 9:11:59 AM (2 occurrences) Last logged: 9:11:59 AM
> > alexaapi.get_devices_gql((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",) alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",)
> > This is with HA 2025.11.2 and AMP 5.7.13
> 
> This is a completely different error that is the result of `get_network_devices` receiving error message "Too many requests" rather than a list of network endpoints that causes `get` to fail and is a known issue with a fix in progress and is not related to this issue.

OK, thanks. Apologies for the confusion.

**Comment by danielbrunt57** [comment]
These errors could be the result of the integration not having any echo devices yet is continuing and tries to get customer history records with an the 

> > > Same here. AMP has the list of echo devices, but not the zigbee devices connected to them. This is in the HA logs during startup:
> > > Logger: alexapy.helpers Source: runner.py:289 First occurred: 9:11:59 AM (2 occurrences) Last logged: 9:11:59 AM
> > > alexaapi.get_devices_gql((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",) alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f4bfed940>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'NoneType' object has no attribute 'get'",)
> > > This is with HA 2025.11.2 and AMP 5.7.13
> > 
> > 
> > This is a completely different error that is the result of `get_network_devices` receiving error message "Too many requests" rather than a list of network endpoints that causes `get` to fail and is a known issue with a fix in progress and is not related to this issue.
> 
> OK, thanks. Apologies for the confusion.

No worries!  I can understand how it all can all be very confusing!

**Comment by danielbrunt57** [comment]
Your error is in get_customer_history_records() and is likely the last call in the sequence:
```
                if should_get_network:
                    _LOGGER.debug(
                        "Alexa entities have been loaded. Prepared for discovery."
                    )
                    api_devices = optional_task_results.pop()
                    if not api_devices:
                        _LOGGER.warning(
                            "%s: Alexa API returned an unexpected response while getting connected devices.",
                            hide_email(email),
                        )
                    alexa_entities = parse_alexa_entities(api_devices)
                    hass.data[DATA_ALEXAMEDIA]["accounts"][email]["devices"].update(
                        alexa_entities
                    )
                    hass.data[DATA_ALEXAMEDIA]["accounts"][email][
                        "should_get_network"
                    ] = False

                    # First run is a special case. Get the state of all entities(including disabled)
                    # This ensures all entities have state during startup without needing to request coordinator refresh
                    for type_of_entity, entities in alexa_entities.items():
                        if type_of_entity == "guard" or extended_entity_discovery:
                            for entity in entities:
                                entities_to_monitor.add(entity.get("id"))
                    entity_state = await get_entity_data(
                        login_obj, list(entities_to_monitor)
                    )
                elif entities_to_monitor:
                    entity_state = optional_task_results.pop()

                if new_devices:
                    auth_info = optional_task_results.pop()
                    _LOGGER.debug(
                        "%s: Found %s devices, %s bluetooth",
                        hide_email(email),
                        len(devices) if devices is not None else "",
                        (
                            len(bluetooth.get("bluetoothStates", []))
                            if bluetooth is not None
                            else ""
                        ),
                    )

            await process_notifications(login_obj, raw_notifications)
            # Process last_called data to fire events
            await update_last_called(login_obj)
```
I think the posted error might be residual fallout from failing to fully authenticate, in which case 'login_obj' would be 'None'.
I trying to fathom how the integration could be proceeding when login failed!

Are there any other errors in your logs prior to the one posted?

**Comment by kiwibhoy** [comment]
Alexa Media Player Issue: sensor.last_alexa Missing Due to Serialization Error
Installation method: Home Assistant OS
Core: 2025.11.1
Supervisor: 2025.11.2
Operating System: 16.3
Frontend: 20251105.0
Alexa Media Player version: 5.7.13

 Background
I discovered this afternoon that my login setup was incorrect. I use Microsoft Authenticator, but I had been entering the latest generated code instead of the one prompted during setup (silly mistake on my part). Once I corrected this and ensured the app password matched my Amazon account, previously missing entities began to appear.
However, one key entity is still missing: sensor.last_alexa.

 Logs from Home Assistant Cloud (after fixing login:

Logger: homeassistant
Source: components/cloud/alexa_config.py:343
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/alexa_config.py", line 330, in async_get_access_token
    details = await self._cloud.alexa_api.access_token()
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/api.py", line 63, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/alexa_api.py", line 63, in access_token
    raise AlexaApiNeedsRelinkError(...) from None
hass_nabucasa.alexa_api.AlexaApiNeedsRelinkError: RefreshTokenNotFound


 Logs from Alexa Media Player
Logger: alexapy.helpers
Source: custom_components/alexa_media/__init__.py:805
alexaapi.get_customer_history_records: TypeError: Cannot serialize non-str key None
alexaapi.get_last_device_serial: TypeError: Cannot serialize non-str key None



 Current Status
- Login confirmed working via MS Authenticator and OTP
- Alexa app and Home Assistant are linked correctly
- Entity sync is working — alarms, timers, reminders, and TTS are functional
- sensor.last_alexa is missing
- Errors persist in get_customer_history_records and get_last_device_serial
- Excluded 5 devices (TVs, recorders, etc.) — no change
- TTS messages confirmed working

**Comment by danielbrunt57** [comment]
This should be resolved now by release 5.8.0

**Comment by kiwibhoy** [comment]
Thanks for the quick response with the v5.8.0 update.
However, I’ve noticed that the "update_last_called" event does not fire, and neither "sensor.last_alexa"  nor  "media_player.last_called_alexa" is created.
Other Alexa entities (alarms, timers, reminders, TTS) are working fine and the serialization errors are still gone, so this seems isolated to the “last called” functionality.
Would you prefer that I open a new issue to track this regression separately, or continue the discussion here?
Regards,
Mike

**Comment by danielbrunt57** [comment]
> Thanks for the quick response with the v5.8.0 update.
> However, I’ve noticed that the "update_last_called" event does not fire, and neither "sensor.last_alexa"  nor  "media_player.last_called_alexa" is created.
> Other Alexa entities (alarms, timers, reminders, TTS) are working fine and the serialization errors are still gone, so this seems isolated to the “last called” functionality.

AMP does not create a `sensor.last_alexa` or a `media_player.last_called_alexa`.
All it does is create a boolean attribute on each Echo media player: `last_called`: `True|False`.
On every polling cycle (default 10 minutes), it calls the service `update_last_called` which retrieves voice history records to determine the last called device and resets the Echo's attribute flag `last_called` appropriately.  There is also an action users can run to perform the same function (`alexa_media.update_last_called`).
