### ISSUE TITLE
all echos are unavailable since latest core (2025.11.3) update

### ISSUE THREAD

**Issue by bEdA8101** [alandtse/alexa_media_player#3161]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2SV via Authenticator App](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (not 2SV OTP via SMS) enabled?  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by poudenes** [comment]
EDIT: My fault I was looking at the supervisor version haha

_Also for HA 2025.11.4_ (this is not correct)

**Comment by MaJerle** [comment]
There is no `HA 2025.11.4` release.

**Comment by eavargasgo** [comment]
Same here. Reverting to 2025.11.2 doesn't solve the problem.

**Comment by MaJerle** [comment]
> Same here. Reverting to 2025.11.2 doesn't solve the problem.

It is not HA issue.

**Comment by eavargasgo** [comment]
I disagree with this; the AMP integration worked correctly in my HA 2025.11.2, and it broke after updating to 2025.11.3.

I understand that AMP is an HACS integration, but the important point is that an HA Core update broke it.

Sincerely,

Evargas
________________________________
De: Tilen Majerle ***@***.***>
Enviado: domingo, 23 de noviembre de 2025 6:00 a. m.
Para: alandtse/alexa_media_player ***@***.***>
Cc: eavargasgo ***@***.***>; Comment ***@***.***>
Asunto: Re: [alandtse/alexa_media_player] all echos are unavailable since latest core (2025.11.3) update (Issue #3161)

[https://avatars.githubusercontent.com/u/405717?s=20&v=4]MaJerle left a comment (alandtse/alexa_media_player#3161)<https://github.com/alandtse/alexa_media_player/issues/3161#issuecomment-3567821451>

Same here. Reverting to 2025.11.2 doesn't solve the problem.

It is not HA issue.

**Comment by INVADIA666** [comment]
same here, just updated to 11.3 and all the entities are unavailable, this is a constant issue with every HA core update. I hope the devs find a stable solution.

**Comment by MaJerle** [comment]
> I disagree with this; the AMP integration worked correctly in my HA 2025.11.2, and it broke after updating to 2025.11.3.
> 
> I understand that AMP is an HACS integration, but the important point is that an HA Core update broke it.
> 
> Sincerely,
> 
> Evargas
> […](#)

It worked for me this morning CET, about 5h ago, HA version `2025.11.3`. The weather forecast was correctly announced from HA. Then about 2h later, I noticed entities are all unavailable

Logs show there must be Amazon problem together with AMP integration.

Edit: Issue is related with AWS returning error code 400 and then integration trying to print debug message with the `len` on a `NoneType`. Indeed nothing to do with the HA core. Pull request is on-going.

https://github.com/alandtse/alexa_media_player/pull/3155
https://github.com/alandtse/alexa_media_player/pull/3160

Temporary fix: https://github.com/alandtse/alexa_media_player/issues/3162#issuecomment-3568081333

**Comment by danielbrunt57** [comment]
> same here, just updated to 11.3 and all the entities are unavailable, this is a constant issue with every HA core update. I hope the ~~devs~~ contributors find a stable solution.

We're always trying...

**Comment by danielbrunt57** [comment]
> I disagree with this; the AMP integration worked correctly in my HA 2025.11.2, and it broke after updating to 2025.11.3. I understand that AMP is an HACS integration, but the important point is that an HA Core update broke it.

Did you have to change anything in the AMP integration in HA 2025.11.2 to get it to work?

**Comment by INVADIA666** [comment]
> > same here, just updated to 11.3 and all the entities are unavailable, this is a constant issue with every HA core update. I hope the ~devs~ contributors find a stable solution.
> 
> We're always trying...

I know guys , you're very patient with this . we all truly appreciate.. I tried reverting to prev version of AMP , didn't work neither..  it was working perfectly with 11.2 HA core, it broke after updating to 11.3 .

**Comment by eavargasgo** [comment]
No. Things were working fine with Core 2025.11.2 and AMP 5.7.13, and it broke when I upgraded to 2025.11.3
________________________________
De: Daniel ***@***.***>
Enviado: domingo, 23 de noviembre de 2025 7:25 a. m.
Para: alandtse/alexa_media_player ***@***.***>
Cc: eavargasgo ***@***.***>; Comment ***@***.***>
Asunto: Re: [alandtse/alexa_media_player] all echos are unavailable since latest core (2025.11.3) update (Issue #3161)

[https://avatars.githubusercontent.com/u/49846893?s=20&v=4]danielbrunt57 left a comment (alandtse/alexa_media_player#3161)<https://github.com/alandtse/alexa_media_player/issues/3161#issuecomment-3567901980>

I disagree with this; the AMP integration worked correctly in my HA 2025.11.2, and it broke after updating to 2025.11.3. I understand that AMP is an HACS integration, but the important point is that an HA Core update broke it.

Did you have to change anything in the AMP integration in HA 2025.11.2 to get it to work?

**Comment by some-guy-23** [comment]
I'm having the same issue on last month's version of HA Core. I think it's a problem that begins after rebooting HA, which is confusing things. 

This is the error I'm getting, which seems to be root issue? 

https://github.com/alandtse/alexa_media_player/issues/3137

**Comment by Rainor20202** [comment]
FYI - looks like an AWS issue - this outage which just happened to me today 11/23/2025.  I did NOT update HA core or supervisor.  Stopped working again.

Installation method Home Assistant OS
Core 2025.8.3
Supervisor 2025.11.4
Operating System 16.1
Frontend 20250811.1

**Comment by kj4qyf** [comment]
I hope that someone is working on a solution.

**Comment by fotis3d** [comment]
I am having the same issue since latest HA update 2025.11.3. I do not think its an AWS issue cause the scripts from Echo Dot to HA run correctly. the media player does not work

**Comment by rodolfomachado** [comment]
Same problem here.
It started when I upgraded to Core 2025.11.3.
I downgraded and the problems remains

**Comment by NoahLikes2Code** [comment]
Same here. Removed integration and re-added. Now it doesn't show any entities/devices.

<img width="1361" height="313" alt="Image" src="https://github.com/user-attachments/assets/6af3e611-4386-4e32-b91f-6c271b755df2" />

My workaround to not use this integration...
1. create a button in HA.
2. expose that button to Alexa via the Voice Assistant settings in HA.
3. create a routine in Alexa that uses that button as a trigger to do whatever (in my case, having my echo devices say something).

**Comment by makokiller** [comment]
This intergration has always been gay!

**Comment by 12oclocker** [comment]
temporary fix here... https://github.com/alandtse/alexa_media_player/issues/3162#issuecomment-3568081333

**Comment by danielbrunt57** [comment]
> This integration has always been gay!

We try and keep it on the straight and narrow despite its tendencies!! 😜

**Comment by danielbrunt57** [comment]
This should be resolved by AMP Release v5.8.0.

**Comment by eavargasgo** [comment]
Problem solved with AMP 5.8.0. Thank you very much. Great work!

**Comment by poudenes** [comment]
Some little off-topic question: Since the issue and latest update of AMP integration the "do not disturb switch" isn't there anymore. What i know this was created also by AMP integration.

**Comment by danielbrunt57** [comment]
> Some little off-topic question: Since the issue and latest update of AMP integration the "do not disturb switch" isn't there anymore. What i know this was created also by AMP integration.

Not totally off-topic IMO but anyway...
Mine is present:

<img width="269" height="188" alt="Image" src="https://github.com/user-attachments/assets/964ca833-c7c9-4b7b-a2b4-d3a960f31d5f" />

This might be unrelated but a new version of `alexapy` has been released just after AMP 5.8.0.  After installing AMP v5.8.0, I immediately modified my manifest JSON to change the `alexapy` required version to `1.29.10`.  Try that, restart and see what happens...

**Comment by poudenes** [comment]
> > Some little off-topic question: Since the issue and latest update of AMP integration the "do not disturb switch" isn't there anymore. What i know this was created also by AMP integration.
> 
> Not totally off-topic IMO but anyway...
> Mine is present:
> 
> <img width="269" height="188" alt="Image" src="https://github.com/user-attachments/assets/964ca833-c7c9-4b7b-a2b4-d3a960f31d5f" />
> 
> This might be unrelated but a new version of `alexapy` has been released just after AMP 5.8.0.  After installing AMP v5.8.0, I immediately modified my manifest JSON to change the `alexapy` required version to `1.29.10`.  Try that, restart and see what happens...

Changed it and restart HA. Still nothing. Maybe remove everything and reinstall the integration?

**Comment by danielbrunt57** [comment]
> Changed it and restart HA. Still nothing. Maybe remove everything and reinstall the integration?

Perhaps.  Are there any _restored_ entities attached to the integration that are unavailable.  you should be able to delete those.  Also, are any that are name with a "_2" appended?  If so, after deleting the restored,unavilable ones, you should be able to rename the "_2" ones removing the "_2'.  If after all that a restart, they're still not there...  Oh, wait a second! Did you enable the integration configuration flag "extended_entity_discovery" with the description "Include devices connected via Echo" when you configured it?
